import React, { useState, useEffect } from 'react';
import { BlogPost } from '../types';
import { getBlogs } from '../services/storageService';
import BlogCard from '../components/BlogCard';
import ChartComponent from '../components/ChartComponent';

const Home: React.FC = () => {
  const [blogs, setBlogs] = useState<BlogPost[]>([]);
  const [search, setSearch] = useState('');

  // Re-fetch blogs whenever component mounts to ensure fresh list (if auto-blog ran)
  useEffect(() => {
    setBlogs(getBlogs());
    
    // Set up an interval to refresh the blog list periodically 
    // This allows the user to see new auto-blogs appear if they are on the home page
    const interval = setInterval(() => {
      setBlogs(getBlogs());
    }, 5000); 

    return () => clearInterval(interval);
  }, []);

  const filteredBlogs = blogs.filter(b => 
    b.title.toLowerCase().includes(search.toLowerCase()) || 
    b.tags.some(t => t.toLowerCase().includes(search.toLowerCase()))
  );

  return (
    <div className="space-y-12 pb-12">
      {/* Hero Section */}
      <section className="bg-gradient-to-b from-trade-900 to-trade-800 py-16 px-4 relative overflow-hidden">
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 items-center relative z-10">
          <div>
            <span className="text-trade-accent font-semibold tracking-wider uppercase text-sm">Automated Market Intelligence</span>
            <h1 className="text-5xl font-bold text-white mt-4 mb-6 leading-tight">
              Master the Markets with <span className="text-transparent bg-clip-text bg-gradient-to-r from-trade-accent to-blue-400">AI-Powered</span> Analysis
            </h1>
            <p className="text-gray-400 text-lg mb-8 max-w-lg">
              Get real-time Forex, Crypto, and Stock updates generated by advanced AI algorithms. Powered by TradeNexus & Trade Maven.
            </p>
            <div className="flex space-x-4">
              <input 
                type="text" 
                placeholder="Search symbol (e.g., BTC, EURUSD)" 
                className="bg-trade-700 border border-trade-600 text-white px-4 py-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-trade-accent w-full max-w-xs"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
          </div>
          <div className="relative">
            <div className="absolute -inset-1 bg-gradient-to-r from-trade-accent to-blue-600 rounded-lg blur opacity-25"></div>
            <div className="relative bg-trade-900 rounded-lg p-2 shadow-2xl border border-trade-700">
               <ChartComponent />
               <div className="grid grid-cols-3 gap-2 mt-2">
                 <div className="bg-trade-800 p-3 rounded text-center">
                    <p className="text-xs text-gray-500">EUR/USD</p>
                    <p className="text-trade-accent font-bold">+0.45%</p>
                 </div>
                 <div className="bg-trade-800 p-3 rounded text-center">
                    <p className="text-xs text-gray-500">BTC/USD</p>
                    <p className="text-trade-danger font-bold">-1.20%</p>
                 </div>
                 <div className="bg-trade-800 p-3 rounded text-center">
                    <p className="text-xs text-gray-500">XAU/USD</p>
                    <p className="text-trade-gold font-bold">+0.15%</p>
                 </div>
               </div>
            </div>
          </div>
        </div>
      </section>

      {/* Latest Blogs */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-end mb-8">
          <div>
            <h2 className="text-3xl font-bold text-white">Latest Market Insights</h2>
            <p className="text-gray-400 mt-2">AI-Generated technical analysis and news.</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {filteredBlogs.length > 0 ? (
            filteredBlogs.map(blog => (
              <BlogCard key={blog.id} blog={blog} />
            ))
          ) : (
            <div className="col-span-full text-center py-12 text-gray-500">
              No blogs found matching your search.
            </div>
          )}
        </div>
      </section>
    </div>
  );
};

export default Home;